<?php
// $Id: jw_player_youtube.install,v 0.1 2011/03/03 13:57:42 skilip Exp $

/**
 * @file
 * Install, update and uninstall functions for the jw_player_youtube module.
 */

/**
 * Implements hook_field_schema().
 */
function jw_player_youtube_field_schema($field) {
  return array(
    'columns' => array(
      'youtube_id' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'sortable' => TRUE
      ),
    ),
  );
}
